<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

## Task E

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [ ]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train,X_cv,y_train,y_cv = train_test_split(X_train,y_train,test_size=0.25,random_state= 12)


In [ ]:
clf = SVC(C=100,gamma=0.001)
clf.fit(X_train,y_train)

SVC(C=100, gamma=0.001)

In [ ]:
clf.support_.shape

(549,)

In [ ]:
clf.support_vectors_.shape,X.shape,y.shape

((549, 5), (5000, 5), (5000,))

In [ ]:
clf.dual_coef_.shape

(1, 549)

In [ ]:
clf.intercept_

array([-1.35390294])

In [ ]:
def rbf_kernel(x,xq,gamma):
    l2_norm = np.linalg.norm(x-xq)**2
    return np.exp(-gamma*l2_norm)

In [ ]:
def decision_function(x_cv,supp_vec,dual_coef,intercept,gamma):
    fcv = []
    
    for xq in x_cv:
        sigma_sum = 0

        for idx, vec in enumerate(supp_vec):
            l2_norm = np.linalg.norm(vec-xq)**2

            sigma_sum += dual_coef[0,idx] * np.exp(-gamma*l2_norm)
        sigma_sum += intercept[0]
        fcv.append(sigma_sum)

    return np.array(fcv)

In [ ]:
gamma = 0.001
decision_function(X_cv,clf.support_vectors_,clf.dual_coef_,clf.intercept_,gamma)

array([-3.05664941, -2.99023791,  2.39099664, -1.3506723 ,  2.08692227,
        1.1651296 , -3.58704803, -1.37076254,  0.79035216, -1.1055276 ,
       -3.78093968, -1.44547516, -0.39899742, -3.68331668, -2.92873745,
        1.46705015, -1.65034325, -3.35764998,  1.70199562, -0.05888766,
       -0.81776117,  0.60570108, -3.32262477,  1.1018464 , -3.48424565,
       -3.68781668,  1.42603836,  0.9664406 , -3.34733083, -1.90215035,
       -2.84850381,  1.13803869, -0.67789657, -3.7487094 , -2.00216652,
        1.48081788,  1.49584053,  1.9239545 ,  1.01949964, -2.47285066,
       -3.49989487, -1.10497453, -2.96113157, -4.0645838 , -2.22497469,
       -2.04735907, -2.89265391, -3.93150644, -0.04112584, -1.50659417,
       -1.92458242, -2.03896474,  1.49494184,  2.14675624, -3.28252533,
        1.52333556, -0.03977944, -3.45468459, -2.30305527, -1.85095582,
       -2.59822267,  1.79249102, -3.12204128,  0.4644319 , -2.26420257,
       -2.42156248, -2.54531711, -3.53963609,  0.84693563, -3.24

In [ ]:
clf.decision_function(X_cv)

array([-3.05664941, -2.99023791,  2.39099664, -1.3506723 ,  2.08692227,
        1.1651296 , -3.58704803, -1.37076254,  0.79035216, -1.1055276 ,
       -3.78093968, -1.44547516, -0.39899742, -3.68331668, -2.92873745,
        1.46705015, -1.65034325, -3.35764998,  1.70199562, -0.05888766,
       -0.81776117,  0.60570108, -3.32262477,  1.1018464 , -3.48424565,
       -3.68781668,  1.42603836,  0.9664406 , -3.34733083, -1.90215035,
       -2.84850381,  1.13803869, -0.67789657, -3.7487094 , -2.00216652,
        1.48081788,  1.49584053,  1.9239545 ,  1.01949964, -2.47285066,
       -3.49989487, -1.10497453, -2.96113157, -4.0645838 , -2.22497469,
       -2.04735907, -2.89265391, -3.93150644, -0.04112584, -1.50659417,
       -1.92458242, -2.03896474,  1.49494184,  2.14675624, -3.28252533,
        1.52333556, -0.03977944, -3.45468459, -2.30305527, -1.85095582,
       -2.59822267,  1.79249102, -3.12204128,  0.4644319 , -2.26420257,
       -2.42156248, -2.54531711, -3.53963609,  0.84693563, -3.24