<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:

def matrix_mul(A, B):
    if len(A[0]) == len(B):
      mul_ab = []
      for i in range(len(A)):# iterating by number of rows in A
        temp = []

        for j in range(len(B[0])): # iterating by number of columns in B
          prod = 0

          for k in range(len(B)): # multiplying and adding elements of A(rows) and B(columns) 
            prod += A[i][k] * B[k][j]

          temp.append(prod)
          
        mul_ab.append(temp)
        
          
    else:
      return "A*B = Not possible" 

    return mul_ab


# Example 1

In [ ]:
A = [[1, 3, 4],
    [2, 5, 7],
    [5, 9, 6]]
B = [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]
matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

# Example 2

In [ ]:
A   = [[1, 2],
      [3, 4]]
B   = [[1, 2, 3, 4, 5],
      [5, 6, 7, 8, 9]]
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

# Example 3

In [ ]:
A   = [[1, 2],
       [3, 4]]
B   = [[1, 4],
      [5, 6],
      [7, 8],
      [9, 6]]
matrix_mul(A, B)  

'A*B = Not possible'

<h1> Q2: Proportional Sampling -</h3> Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
from functools import reduce


def add_1(x, y): 
  # adds 2 elements
  return x+y


def proportional_sampling(lst): 
  # Returns a list of proportional sample of lst
  s = sum(lst)
  di = []
  di_cum = []

  for num in lst:
    di.append(num/s)
    di_cum.append(reduce(add_1, di))
  return di_cum


def pick_a_number_from_list(lst):
    # for picking an element from a list with the probability propotional to its magnitude
  r = uniform(0, 1)
  for i in range(len(proportional_sampling(lst))):
    if r <= proportional_sampling(lst)[i]:
      return lst[i]


def sampling_based_on_magnitued(lst):
  # Gives a list of 100 trails of picking a number from list A
  sample =[]
  for i in range(0,100):
    number = pick_a_number_from_list(lst)
    sample.append(number)
  return sample


A = [0,5,27,6,13,28,100,45,10,79]

sample_list = sampling_based_on_magnitued(A)
for num in sorted(A):
  print(num,'\t', sample_list.count(num)) #printing the elements and the number of times they are picked


0 	 0
5 	 0
6 	 0
10 	 3
13 	 3
27 	 5
28 	 8
45 	 21
79 	 27
100 	 33


<h1> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re


def replace_digits(string):
    string_match = re.findall('\d', string)
    output_string = ''
    for i in range(len(string_match)):
      output_string += '#'
    return output_string  # modified string which is after replacing the # with digits

print(replace_digits('123'))            # exp 1
print(replace_digits('a2b3c4 '))        # exp 2
print(replace_digits('abc '))           # exp 3
print(replace_digits('#2a$#b%c%561#'))  # exp 4

###
###

####


<h1> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>c. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

# INPUT

In [2]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

In [4]:
def display_dash_board(students, marks):
    '''returns lists of tuples of students and marks
     of top 5 last 5 and between 25 and 75 percentile'''

    sorted_marks = sorted(marks, reverse = True)

    top_5_students = []
    for num in sorted_marks[0:5]:
      ind = marks.index(num)
      top_5_students.append(ind)

    sorted_marks = sorted(marks)   
    least_5_students = []
    for num in sorted_marks[0:5]:
      ind = marks.index(num)
      least_5_students.append(ind)

    students_within_25_and_75 = []

    diff = max(Marks)-min(Marks)
    for num in sorted_marks:
      if (num > 0.25*diff) and (num < 0.75*diff):
        ind = marks.index(num)
        students_within_25_and_75.append(ind)

    return top_5_students, least_5_students, students_within_25_and_75


top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
#top 5
print('a')
for num in top_5_students:
  print(Students[num],Marks[num])

#least 5
print('b')
for num in least_5_students:
  print(Students[num],Marks[num])

#between 25 and 75
print('c')
for num in students_within_25_and_75:
  print(Students[num],Marks[num])

a
student8 98
student10 80
student2 78
student5 48
student7 47
b
student3 12
student4 14
student9 22
student6 43
student1 45
c
student9 22
student6 43
student1 45
student7 47
student5 48


<h1> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math as m


def cos_dis(point1,point2):
  '''
  returns cosine distance
  '''
  x, y = point1
  p, q = point2
  return m.acos((x*p+y*q)/(m.sqrt(x*x + y*y) * m.sqrt(p*p + q*q)))


def closest_points_to_p(S, P):
  '''
  gives 5 closest points of all the given points to given point
  '''
  dis = {}  # dict with distace as keys and points as value
  
  for num in S:
    dis[cos_dis(num, P)] = num
  
  closest_points = []

  for num in sorted(dis)[0:5]: #sorted(dis) returns the sorted keys of dis
    closest_points.append(dis[num])

  return closest_points 


#INPUT
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

points = closest_points_to_p(S, P)
print(*points, sep='\n') #prints list

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h1> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math


def line_coef(s):
  lst = list(s.split('x'))
  a = lst[0]
  b,c = lst[1].split('y')
  return float(a),float(b),float(c)


def i_am_the_one(red,blue,line):
  a,b,c = line_coef(line)

  for point_r in red:
    x, y = point_r
    r = a*x + b*y + c
    
    for point_b in blue:
      x, y = point_b
      bl = a*x + b*y + c

      if r*bl > 0 :
        return 'no'
  return 'yes'


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

yes
no
no
yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results


def curve_smoothing(string):
  lst = string.split(',')
  index_list = [i for i,ch in enumerate(lst) if ch != '_']
  # if there is single number
  if len(index_list) == 1:
    if index_list[0] == 0 or index_list[0] == len(lst) - 1:
      val = float(lst[index_list[0]])/len(lst)
      for i in range(len(lst)):
          lst[i] = val
    else:
      val = float(lst[index_list[0]]) / (index_list[0] + 1)
      for i in range(0, index_list[0] + 1):
        lst[i] = val
      val = float(lst[index_list[0]]) / (len(lst) - index_list[0])
      for i in range(index_list[0],len(lst)):
        lst[i] = val
  else:
    for i,ind in enumerate(index_list[:-1]):
      if i == 0 and ind != 0:
        val = float(lst[index_list[i]])/(ind + 1)
        for it in range(0,ind+1):
          lst[it] = val      

      val = (float(lst[ind])+float(lst[index_list[i+1]]))/(index_list[i+1]-ind+1)
      for it in range(index_list[i], index_list[i+1]+1):
        lst[it] = val

      if i == (len(index_list) - 2):
        i += 1
        if index_list[i] < (len(lst)-1):
          val = float(lst[index_list[i]])/(len(lst)-index_list[i])
          for it in range(index_list[i],len(lst)):
            lst[it] = val
  return lst


S=  ["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]
for s in S:
  print(s,'\t', curve_smoothing(s))

_,_,_,24 	 [6.0, 6.0, 6.0, 6.0]
40,_,_,_,60 	 [20.0, 20.0, 20.0, 20.0, 20.0]
80,_,_,_,_ 	 [16.0, 16.0, 16.0, 16.0, 16.0]
_,_,30,_,_,_,50,_,_ 	 [10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h1> Q8: Conditional probability</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):

  output =[]
  for pair in all_pairs:
    f,s = pair
    count_fns = 0
    count_s = 0
    for pr in A:
      if pr[0] == f and pr[1] == s:
        count_fns += 1
      if pr[1] == s:
        count_s += 1
    output.append(count_fns/count_s)
  return output


all_pairs = [['F1','S1'],['F1','S2'],['F1','S3'],
            ['F2','S1'],['F2','S2'],['F2','S3'],
            ['F3','S1'],['F3','S2'],['F3','S3'],
            ['F4','S1'],['F4','S2'],['F4','S3'],
            ['F5','S1'],['F5','S2'],['F5','S3']]   

A = [['F1','S1'],['F2','S2'],['F3','S3'],
     ['F1','S2'],['F2','S3'],['F3','S2'],
     ['F2','S1'],['F4','S1'],['F4','S3'],
     ['F5','S1']]

cond_prob_list = compute_conditional_probabilites(A)
for i in range(len(all_pairs)):
  print(all_pairs[i],"\t",cond_prob_list[i])

['F1', 'S1'] 	 0.25
['F1', 'S2'] 	 0.3333333333333333
['F1', 'S3'] 	 0.0
['F2', 'S1'] 	 0.25
['F2', 'S2'] 	 0.3333333333333333
['F2', 'S3'] 	 0.3333333333333333
['F3', 'S1'] 	 0.0
['F3', 'S2'] 	 0.3333333333333333
['F3', 'S3'] 	 0.3333333333333333
['F4', 'S1'] 	 0.25
['F4', 'S2'] 	 0.0
['F4', 'S3'] 	 0.3333333333333333
['F5', 'S1'] 	 0.25
['F5', 'S2'] 	 0.0
['F5', 'S3'] 	 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    string_set_1 = set(S1.split(' '))
    string_set_2 = set(S2.split(' '))
    a = len(string_set_1.intersection(string_set_2))
    b = list(string_set_1-string_set_2)
    c = list(string_set_2-string_set_1)
    return a, b, c


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

print(*string_features(S1,S2), sep = '\n')

7
['5', 'first', 'F']
['second', '3', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math as m

def compute_log_loss(A):
  sigma = 0
  for pair in A:
    y, y_score = pair
    sigma += y*m.log10(y_score) + (1-y)*m.log10(1-y_score) 
  return -1 * sigma/len(A)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
